[build]
  command = "npm ci && npm run build"
  publish = "build"    # or "dist" if that’s your output

[build.environment]
  NODE_VERSION = "22"        # any Node 20.x LTS
  NPM_FLAGS = "--no-audit --no-fund"